### ISSUE TITLE
fatal: [localhost -> 10.0.1.6]: UNREACHABLE

### ISSUE THREAD

**Issue by technoluc** [rpenziol/proxmox-kubernetes-bootstrap#2]
When running `ansible-playbook proxmox_k8s_new_master_vm.yml` i get this error

```
TASK [Fix broken VM boot order to not reboot to PXE. Must be run after first VM boot.] *********************************
fatal: [localhost -> 10.0.1.6]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: LOCALUSERNAME@10.0.1.6: Permission denied (publickey,password).", "unreachable": true}
```

My host running proxmox is on 10.0.1.6
My host configuring this is on 10.0.1.66
LOCALUSERNAME is the username used to deploy ansible playbook, that username doesn't exist on 10.0.1.6.

should inventories/hosts.yml have the address of my proxmox machine or my local machine with ansible? Am i supposed to run this as root? Because then i get the same error with root instead of LOCALUSERNAME. 
Or am i missing something else?

Help would be appreciated! 

these are my edited files

group_vars/all.yml

```
ansible_python_interpreter: /usr/bin/python3

proxmox_template_name: ubuntu-20.04-server

proxmox_details:
  host_ip: 10.0.1.6
  host_ssh_port: 22
  host_url: "https://10.0.1.6:8006/"
  api_user: root@pam
  api_password: SECRETPASSWD
  node: proliant
  storage: local-lvm
```

inventories/hosts.yml

```
---

all:
  hosts:
    proxmox:
      ansible_host: 10.0.1.6
      ansible_port: 22

  children:
    physical:
      hosts:
        proxmox:

    k8s-cluster:
      children:
        kube-master:
        kube-node:

```

inventories/proxmox.json

```
{
    "url": "https://10.0.1.6:8006/",
    "username": "root@pam",
    "password": "SECRETPASSWD",
    "qemu_interface": "ens18",
    "validateCert": false
}
```
